name: Publish Composer Package to Artifactory

on:
  release:
    types:
      - published

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: read
  security-events: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: neta-io/github-actions-workflows/.github/workflows/sw-publish-package.yml@master
    secrets:
      ARTIFACTORY_API_KEY: ${{ secrets.ARTIFACTORY_API_KEY }}
